### ISSUE TITLE
Can we have a push request tagged..

### ISSUE THREAD

**Issue by dreamerNcoder** [emmerich/flot-orderBars#8]
Hi, 
Its not a issue.. but did not know where to put it..
Can you please tag atleast latest commits.. ?

**Comment by emmerich** [comment]
Not sure I understand the question. Why do you need a tag?

**Comment by machineghost** [comment]
Not sure if this is what dreamerNCoder is referring to, but your project has never been released ... in the sense that it has no releases.  This makes it difficult if not impossible to use your plugin with tools such as NodeJS.  If you could just create even a single release it would be helpful.

**Comment by emmerich** [comment]
Ah, understood. I've added a package.json and tagged the current version at 1.0.0

**Comment by machineghost** [comment]
Awesome, thanks.
